### ISSUE TITLE
Fanboy’s Annoyance breaks Drupal admin

### ISSUE THREAD

**Issue by prudloff-insite** [easylist/easylist#12695]
### List the website(s) you're having issues:

Any Drupal 9 website where I can access the admin.

### What happens?

Fanboy’s Annoyance prevents this Drupal file from being loaded: https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/assets/vendor/jquery.ui/ui/disable-selection-min.js
This breaks several functionalities of the Drupal admin because it prevents dialogs from opening correctly:

```
Uncaught TypeError: this._handles.disableSelection is not a function
    jQuery 20
    openDialog dialog.js:31
    showModal dialog.js:51
    openDialog dialog.ajax.js:94
    success ajax.js:446
    success ajax.js:444
    success ajax.js:241
    jQuery 6
    eventResponse ajax.js:339
    Ajax ajax.js:279
    jQuery 8
    Ajax ajax.js:272
    ajax ajax.js:127
    bindAjaxLinks ajax.js:161
    bindAjaxLinks ajax.js:142
    attach ajax.js:42
    attachBehaviors drupal.js:27
    attachBehaviors drupal.js:24
    <anonymous> drupal.init.js:29
    listener drupal.init.js:17
    domReady drupal.init.js:24
    <anonymous> drupal.init.js:28
    <anonymous> drupal.init.js:31
resizable.js:333:16
```

### List Subscriptions you're using:

```
listset (total-discarded, last updated): 
  added: 
    fanboy-annoyance: 76273-37337, 23h.21m
    fanboy-cookiemonster: 37158-85, 23h.23m
  default: 
    user-filters: 0-0, never
    ublock-filters: 32941-187, 23h.23m
    ublock-badware: 4213-0, 23h.23m
    ublock-privacy: 240-0, 23h.23m
    ublock-abuse: 76-0, 23h.23m
    ublock-unbreak: 1848-0, 23h.23m
    easylist: 68773-650, 23h.23m
    easyprivacy: 27447-580, 23h.23m
    plowe-0: 3640-3, 23h.23m
    FRA-0: 29619-355, 23h.23m
    urlhaus-1: 4999-0, 23h.23m
```
### Your settings

- OS/version: Linux Mint 20
- Browser/version: Firefox 102.0.1
- Adblock Extension/version: uBlock Origin 1.43.0

### Other details:

This seems to be caused by https://github.com/easylist/easylist/commit/4e90a670a59e80e9dca7389da5bfbb39049306df.
